spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerdbTest
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  