server:
  port: 9090

logging:
  pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    com.retailer.reward.controller: TRACE

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  